version: "3.8"

services:
  api:
    build: .
    container_name: node_api
    restart: always
    ports:
      - "4001:4001"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ../Frontend/.
      dockerfile: Dockerfile  
    container_name: react_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge

