apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
type: Opaque
data:
  DB_USERNAME: cG9zdGdyZXM=          #postgres
  DB_PASSWORD: Y2xvdWRAMTIz   #cloud@123       
  DB_NAME: Y2xvdWQ=     #cloud          

